version: "2"
services:
  web:
    build: .
    image: users-service
    restart: always
    # Run Debug Server
    command: python manager.py runserver --port 8000 --host 0.0.0.0 --reload
    links:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: myapp
      FLASK_DEBUG: 1
      SECRET_KEY: secret_dev_123
    container_name: users-service
  db:
    image: mysql
    container_name: database-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: myapp
