"""empty message

Revision ID: b905e88b5cb0
Revises: 49dc4e378d
Create Date: 2016-07-03 13:27:09.152230

"""

# revision identifiers, used by Alembic.
revision = 'b905e88b5cb0'
down_revision = '49dc4e378d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
